/********************************************************************************/
/********************************************************************************/
/**   ALEKSANDER KSIAZEK i PAWEL LIPSKI   *   MASZ_GO_BOT   *   VERSION  1.0   **/
/********************************************************************************/
/********************************************************************************/

#ifndef _MELODIE_H
#define _MELODIE_H

#include "tone_definitions.h"

/********************************************************************************/
//const char TEXT_SONG0[]       = "Intel Sound before Pause";
int Intel1[][2] = {
			{4,TONE_g0},
			{0,0}
        };
/********************************************************************************/
//const char TEXT_SONG1[]       = "Intel Sound after Pause";
int Intel2[][2] = {
			{6,TONE_d0},
			{6,TONE_g0},
			{6,TONE_d0},
			{3,TONE_a0},
			{0,0}
        };

/********************************************************************************/
//const char TEXT_SONG2[]       = "William Tell Overture";
// {duration, note}
// duration 8 means eighth note allegro
int William[][2] = {
			{8,TONE_g},
			{8,TONE_g},
			{4,TONE_g},
			{8,TONE_g},
			{8,TONE_g},
			{4,TONE_g},
			{8,TONE_g},
			{8,TONE_g},
			{4,TONE_c0},
			{4,TONE_d0},
			{4,TONE_e0},
			{8,TONE_g},
			{8,TONE_g},
			{4,TONE_g},
			{8,TONE_g},
			{8,TONE_g},
			{4,TONE_c0},
			{8,TONE_e0},
			{8,TONE_e0},
			{4,TONE_d0},
			{4,TONE_b},
			{4,TONE_g},
			{8,TONE_g},
			{8,TONE_g},
			{4,TONE_g},
			{8,TONE_g},
			{8,TONE_g},
			{4,TONE_g},
			{8,TONE_g},
			{8,TONE_g},
			{4,TONE_c0},
			{4,TONE_d0},
			{4,TONE_e0},
			{8,TONE_c0},
			{8,TONE_e0},
			{2,TONE_g0},
			{8,TONE_f0},
			{8,TONE_e0},
			{8,TONE_d0},
			{4,TONE_c0},
			{4,TONE_e0},
			{4,TONE_c0},
			{1, -1},
			{0,0}
        };
/********************************************************************************/
//const char TEXT_SONG3[]       = "In the Hall of the Mountain King";
// {duration, note}
// duration 8 means eighth note allegro
int King[][2] = {
			{2,TONE_d_g},
			{2,TONE_a_g},
			{2,TONE_d_g},
			{2,TONE_a_g},
			{2,TONE_d_g},
			{2,TONE_a_g},
			{2,TONE_d_g},
			{2,TONE_a_g},

			{4,TONE_d},
			{4,TONE_e},
			{4,TONE_f},
			{4,TONE_g},
			{4,TONE_a},
			{4,TONE_f},
			{2,TONE_a},
			{4,TONE_gx},
			{4,TONE_e},
			{2,TONE_gx},
			{4,TONE_g},
			{4,TONE_xd},
			{2,TONE_g},
			{4,TONE_d},
			{4,TONE_e},
			{4,TONE_f},
			{4,TONE_g},
			{4,TONE_a},
			{4,TONE_f},
			{4,TONE_a},
			{4,TONE_d0},
			{4,TONE_c0},
			{4,TONE_a},
			{4,TONE_f},
			{4,TONE_a},
			{1,TONE_c0},

			{4,TONE_d},
			{4,TONE_e},
			{4,TONE_f},
			{4,TONE_g},
			{4,TONE_a},
			{4,TONE_f},
			{2,TONE_a},
			{4,TONE_gx},
			{4,TONE_e},
			{2,TONE_gx},
			{4,TONE_g},
			{4,TONE_xd},
			{2,TONE_g},
			{4,TONE_d},
			{4,TONE_e},
			{4,TONE_f},
			{4,TONE_g},
			{4,TONE_a},
			{4,TONE_f},
			{4,TONE_a},
			{4,TONE_d0},
			{4,TONE_c0},
			{4,TONE_a},
			{4,TONE_f},
			{4,TONE_a},
			{1,TONE_c0},

			{4,TONE_a},
			{4,TONE_b},
			{4,TONE_cx0},
			{4,TONE_d0},
			{4,TONE_e0},
			{4,TONE_c0},
			{2,TONE_e0},
			{4,TONE_f0},
			{4,TONE_cx0},
			{2,TONE_f0},
			{4,TONE_e0},
			{4,TONE_c0},
			{2,TONE_e0},

			{4,TONE_a},
			{4,TONE_b},
			{4,TONE_cx0},
			{4,TONE_d0},
			{4,TONE_e0},
			{4,TONE_c0},
			{2,TONE_e0},
			{4,TONE_f0},
			{4,TONE_cx0},
			{2,TONE_f0},
			{1,TONE_e0},

			{4,TONE_a},
			{4,TONE_b},
			{4,TONE_cx0},
			{4,TONE_d0},
			{4,TONE_e0},
			{4,TONE_c0},
			{2,TONE_e0},
			{4,TONE_f0},
			{4,TONE_cx0},
			{2,TONE_f0},
			{4,TONE_e0},
			{4,TONE_c0},
			{2,TONE_e0},

			{4,TONE_a},
			{4,TONE_b},
			{4,TONE_cx0},
			{4,TONE_d0},
			{4,TONE_e0},
			{4,TONE_c0},
			{2,TONE_e0},
			{4,TONE_f0},
			{4,TONE_cx0},
			{2,TONE_f0},
			{1,TONE_e0},

			{8,TONE_d0},
			{8,TONE_e0},
			{8,TONE_f0},
			{8,TONE_g0},
			{8,TONE_a0},
			{8,TONE_f0},
			{4,TONE_a0},
			{8,TONE_gx0},
			{8,TONE_e0},
			{4,TONE_gx0},
			{8,TONE_g0},
			{8,TONE_dx0},
			{4,TONE_g0},

			{8,TONE_d0},
			{8,TONE_e0},
			{8,TONE_f0},
			{8,TONE_g0},
			{8,TONE_a0},
			{8,TONE_f0},
			{8,TONE_a0},
			{8,TONE_d1},
			{8,TONE_c1},
			{8,TONE_a0},
			{8,TONE_f0},
			{8,TONE_a0},
			{2,TONE_c1},

			{8,TONE_d0},
			{8,TONE_e0},
			{8,TONE_f0},
			{8,TONE_g0},
			{8,TONE_a0},
			{8,TONE_f0},
			{4,TONE_a0},
			{8,TONE_gx0},
			{8,TONE_e0},
			{4,TONE_gx0},
			{8,TONE_g0},
			{8,TONE_dx0},
			{4,TONE_g0},

			{8,TONE_d0},
			{8,TONE_e0},
			{8,TONE_f0},
			{8,TONE_g0},
			{8,TONE_a0},
			{8,TONE_f0},
			{8,TONE_a0},
			{8,TONE_d1},
			{8,TONE_c1},
			{8,TONE_a0},
			{8,TONE_f0},
			{8,TONE_a0},
			{2,TONE_c1},

			{4,TONE_d_g},
			{4,TONE_d1},
			{4,TONE_d_g},
			{4,TONE_d1},

			{8,TONE_d0},
			{8,TONE_e0},
			{8,TONE_f0},
			{8,TONE_g0},
			{8,TONE_a0},
			{8,TONE_f0},
			{8,TONE_a0},
			{8,TONE_d1},
			{8,TONE_cx1},
			{8,TONE_a0},
			{8,TONE_cx1},
			{8,TONE_e1},
			{2,TONE_d1},

			{4,TONE_d_g},
			{4,TONE_d2},
			{4,TONE_d_g},
			{4,TONE_d2},

			{8,TONE_d1},
			{8,TONE_e1},
			{8,TONE_f1},
			{8,TONE_g1},
			{8,TONE_a1},
			{8,TONE_f1},
			{8,TONE_a1},
			{8,TONE_d2},
			{8,TONE_cx2},
			{8,TONE_a1},
			{8,TONE_cx2},
			{8,TONE_e2},
			{2,TONE_d2},
			{1, -1},
			{0,0}
        };


#endif /* _MELODIE_H */
